name 'container_users'
maintainer 'Ryan Ovrevik'
maintainer_email 'rlo+github@ovrevik.com'
license 'mit'
description 'Installs/Configures container_users'
long_description 'Installs/Configures container_users'
version '0.1.0'
