name 'container_users'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures container_users'
long_description 'Installs/Configures container_users'
version '0.1.0'
